---
- name: Remove Apache from webservers
  hosts: webserver
  tasks:
   - name: Remove Apache
     yum:
       name: httpd
       state: absent

- name: Remove Apache from ubuntuservers
  hosts: ubuntuserver
  tasks:
   - name: Remove Apache
     apt:
       name: apache2
       state: absent
   - name: Remove unwanted Apache2 packages from the system
     apt:
       autoremove: yes
       purge: yes